### ISSUE TITLE
mdl-tooltip only works for the first instance in any one div

### ISSUE THREAD

**Issue by egeland** [Thanood/aurelia-mdl-skeleton-navigation#16]
If you put more than one tooltip on something inside the same `div`, only the first one works.

```
<div>
  <i mdl-tooltip="text: Testing" class="material-icons">mood</i>
  <i mdl-tooltip="text: Testing2" class="material-icons">person</i>
</div>
```

The tooltip will appear on the 'mood' icon, but nothing for the 'person'.

**Comment by Thanood** [comment]
Interesting.. The tooltip has some other bugs as well. I will have a look at it..

**Comment by Thanood** [comment]
It's because of this implementation:

```
componentHandler.upgradeElement(target.parentNode.querySelector('.mdl-tooltip'));
```

It selects only the first. Changed it to:

```
componentHandler.upgradeElement(target.parentNode.querySelector(`.mdl-tooltip[for="${this.element.id}"]`));
```
